require 'rake'
require 'rspec/core/rake_task'
require 'json'


# servers
servers_data = JSON.parse(File.read('servers.json'))
hosts = servers_data



###

#desc "Run serverspec to all hosts"
#task :default => 'serverspec:all'

task :spec    => 'spec:all'
task :default => :spec

namespace :spec do
  targets = []
  Dir.glob('./spec/*').each do |dir|
    next unless File.directory?(dir)
    target = File.basename(dir)
    target = "_#{target}" if target == "default"
    targets << target
  end

  task :all     => targets
  task :default => :all

  targets.each do |target|
    original_target = target == "_default" ? target[1..-1] : target
    desc "Run serverspec tests to #{original_target}"
    RSpec::Core::RakeTask.new(target.to_sym) do |t|
      ENV['TARGET_HOST'] = original_target
      t.pattern = "spec/#{original_target}/*_spec.rb"
    end
  end
end




namespace :serverspec do
  task :all => hosts.keys.map{|r| r.to_sym}
  hosts.each do |host, props|

    desc "Run serverspec to #{host}"
    RSpec::Core::RakeTask.new(host.to_sym) do |t|
      ENV['TARGET_HOST'] = props['host']
      ENV['TARGET_HOST_TYPE'] = props['type']
      ENV['SSH_USER'] = props['user']
      ENV['SSH_PASSWORD'] = props['password']

      #puts "host #{host}"
      #puts "props=#{props.inspect}"


      #
      t.pattern = "spec/{base,#{host}}/*_spec.rb"

      #target_run_list = host_run_list[target_host]
      #recipes = Chef::RunList.new(*target_run_list).expand("_default", "disk").recipes
      #t.pattern = ['../chef/site-cookbooks/{' + recipes.join(',') + '}/spec/*_spec.rb', "spec/#{target_host}/*_spec.rb"]
    end
  end
end
