#!/bin/sh

command_type=sh

if [ -z "$args" ]; then
  args="$ROCANA_CONF_DIR/rocana-supervisor"
fi

command="$ROCANA_LIB_DIR/rocana-agent/rocana-agent --supervisor"

command_sh_main() {
  exec $command $args
}
