#!/bin/sh

command_project="rocana-search"
command_type="java"
command_java_opts="-Djava.net.preferIPv4Stack=true"

# Uncomment the following line if you are using Kerberos
#command_java_opts="${command_java_opts} -Djava.security.auth.login.config=$ROCANA_CONF_DIR/jaas-client.conf"

command_java_main="com.rocana.search.server.SearchApp"
