#!/bin/sh

command_project="rocana-solr"
command_type="java"
command_java_opts="-Djava.net.preferIPv4Stack=true"

# Uncomment the following line if you are using Kerberos
#command_java_opts="${command_java_opts} -Djava.security.auth.login.config=$ROCANA_CONF_DIR/jaas-client.conf"

# Uncomment the following line if this server is managed by Cloudera Manager and is assigned as a Hive gateway
#CLASSPATH=${CLASSPATH}:/etc/hive/conf:/etc/hadoop/conf

command_java_main="com.rocana.consumer.solr.SolrConsumerApp"
